[project]
name = "shipxplorer"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.5",
    "requests-cache>=1.3.0",
    "selectolax>=0.4.6",
]
